### ISSUE TITLE
Question about using chamfer as self-construction loss.

### ISSUE THREAD

**Issue by GostInShell** [dvirginz/DPC#4]
Hi! Thanks for releasing the code of your wonderful work.

For self-construction loss, we are supposed to know the ground-truth point. Then why not just use a supervised loss using the gt point, but a unsupervised chamfer distance. Is there any specific consideration?

**Comment by itailang** [comment]
Dear @GostInShell,

Thank you for your interest in our work!

Your question is great. It is possible to use a supervised loss for self-construction, as you suggested. We used the unsupervised Chamfer loss for the self-construction module so that it will be a counterpart of the cross-construction module, which also uses the unsupervised Chamfer loss. 

In general, the Chamfer loss gives more freedom to the learning process than a strict supervised loss with respect to the ground truth point. But its objective is typically less accurate than the supervised loss, which uses the ground truth data.

That said,  I encourage you to try the supervised loss for self-construction and share your findings with us (if you feel comfortable with that).

Thanks!

**Comment by GostInShell** [comment]
Thanks for the quick reply!

I am not sure whether I have clearly stated my points. I might have misused the word 'ground-truth'. 

On unlabled data, the **ground-truth** correspondences between source and target shapes are unknown. So we have to use the chamfer distance to supervise the cross-construction.

However, for self-construction, the reconstruced point \hat{x}_i (Eq. 7) should resemble the point x_i. So we should be able to directly supervise it via \hat{x}_i-x_i. And this supervision is free (different from the **ground-truth** correspondences in the cross-construction), meaning that DPC remains an unsupervised method even if we use this loss.

As you meantioned above that direct supervision can improve the accuracy, I just wonder why not just use it?

**Comment by itailang** [comment]
I totally understood you in your first comment. What I mean is that I can think of pros and cons for the direct supervision. We did not try it and it would be interesting to see its results.

**Comment by GostInShell** [comment]
Thanks for your answer and insights. I'll share my results here after I try the supervised loss.
